version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fastapi-app-network
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - fastapi-app-network
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
    volumes:
      - redis_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD} --maxmemory 200mb --maxmemory-policy noeviction
    restart: unless-stopped

  # backend-fastapi:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: backend_fastapi
  #   ports:
  #     - '8000:8000'
  #   depends_on:
  #     - chromadb
  #   networks:
  #     - fastapi-app-network
  #   env_file:
  #     - .env

networks:
  fastapi-app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16

volumes:
  postgres_data:
  redis_data:
